name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-app .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app

      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-app
      #       docker stop todo-app || true
      #       docker rm todo-app || true
      #       docker run -d \
      #         --name todo-app \
      #         -e DB_URL=${{ secrets.DB_URL }} \
      #         -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
      #         -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
      #         -p 8080:8080 \
      #         ${{ secrets.DOCKERHUB_USERNAME }}/todo-app
